# This file may be used to create an environment using:
# $ conda env create -f environment.yml
# platform: linux-64
name: fungi
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.6
  - snakemake=3.13.3
  - picard=2.18.29
  - gatk4=4.3.0.0
  - bwa=0.7.17
  - samtools=1.6
  - bcftools=1.9
  - iqtree=2.0.3
  - fastqc=0.11.9
  - pip
  - pip:
    - multiqc==1.14
